### ISSUE TITLE
`rsync` and `scp` completion broken

### ISSUE THREAD

**Issue by indrajitr** [sorin-ionescu/prezto#1378]
### Description

`rsync` and `scp` completion broke after #1356.

### Expected behavior

Tab completion should work for `rsync` and `scp`

### Actual behavior

Tab completion doesn't work anymore

### Versions

  - Prezto commit: a876890afd14304fee06dd87d7ba70412e4780d2
  - ZSH version: 5.3.1
  - OS information: macOS 10.12

**Comment by belak** [comment]
This is the patch I'm playing with:

```
diff --git a/modules/utility/init.zsh b/modules/utility/init.zsh
index e9c20b2..1157bcb 100644
--- a/modules/utility/init.zsh
+++ b/modules/utility/init.zsh
@@ -41,8 +41,8 @@ alias ftp='noglob ftp'
 alias history='noglob history'
 alias locate='noglob locate'
 alias rake='noglob rake'
-alias rsync='noglob rsync_scp_wrap rsync'
-alias scp='noglob rsync_scp_wrap scp'
+alias rsync='noglob rsync_wrap'
+alias scp='noglob scp_wrap'
 # This function wraps rsync and scp so that remote paths are not globbed
 # but local paths are globbed. This is because the programs have their own
 # globbing for remote paths. The wrap function globs args starting in / and ./
@@ -61,6 +61,15 @@ function rsync_scp_wrap {
   esac; done
   command $cmd "${(@)args}"
 }
+function rsync_wrap {
+  rsync_scp_wrap "rsync" "$@"
+}
+function scp_wrap {
+  rsync_scp_wrap "scp" "$@"
+}
+compdef -a _rsync rsync_wrap
+compdef -a _scp scp_wrap
+
 alias sftp='noglob sftp'

 # Define general aliases.
```

I'd love to see a better fix, so I'll ping a few people and see if any ideas come up.

**Comment by belak** [comment]
Fixed in 90071d3ad062c4969b1d2e8512e9238524b90981. I'd like to get a better solution in (if it exists) but I wanted to get this in before I take off this weekend.

**Comment by indrajitr** [comment]
I was actually planning to work on it tonight. But sure, good to have something out!

**Comment by OkanEsen** [comment]
Unfortunately, the error still occurs for me and I think that this is related:

```
/Users/okan/.zprezto/modules/utility/init.zsh:70: command not found: compdef
/Users/okan/.zprezto/modules/utility/init.zsh:71: command not found: compdef
```

**Comment by indrajitr** [comment]
Yep, just encountered this after rebasing the change. `compdef` is being used prematurely.
Fix coming up.

**Comment by indrajitr** [comment]
#1380 should fix this.
